### ISSUE TITLE
option -nodraw- generates an error message

### ISSUE THREAD

**Issue by ericmelse** [benjann/addplot#2]
Dear Ben,

Of your many great packages, `addplot` most certainly is used daily by me and I appreciate it very much.
But, now I am working on cases that require to use it multiple times to the same graph and I do not want to refresh the graph window each time.
So, here comes the option `nodraw` to the rescue. But, alas, when used, I get the error message:
```
option nodraw not allowed
r(198);
```
Like using this example:
```
sysuse auto , clear
scatter mpg turn, jitter(2) msymbol(Oh)
forvalue i = 0(1)1 {
	qui summarize mpg if foreign==`i', meanonly
	addplot: , yline(`r(mean)') norescaling
}
```
which will result in:
![Example_addplot_1](https://github.com/benjann/addplot/assets/3686136/a50d496d-9d03-4997-9136-3e94cdfdf7e7)
But, when I add the option  `nodraw` like:
```
scatter mpg turn, jitter(2) msymbol(Oh)
forvalue i = 0(1)1 {
	qui summarize mpg if foreign==`i', meanonly
	addplot: , yline(`r(mean)') norescaling nodraw
}
```
I get the error message `option nodraw not allowed`.
My assumption is that something triggers this to happen because I am using a Stata version more recent than the one you used during your coding of `addplot` . I now use MP 18.0 Revision 20 Dec 2023.

So, time permitting, could you check this and possibly correct it?

**Comment by benjann** [comment]
Hi Eric, as indicates in `help addplot`, you need to specify `nodraw` as an option to `addplot`, not as an option to the added twoway command. Example:

```
sysuse auto
scatter mpg turn, jitter(2) msymbol(Oh)
forvalue i = 0(1)1 {
    qui summarize mpg if foreign==`i', meanonly
    addplot, nodraw: , yline(`r(mean)') norescaling
}
graph display
```

ben

**Comment by ericmelse** [comment]
Aha! Silly me... But, it works now just perfectly. Thanks for your helping hand.
