### ISSUE TITLE
Using addplot produces 'raggedness' at the edge

### ISSUE THREAD

**Issue by ericmelse** [benjann/addplot#3]
Dear Ben,

While using `addplot` I get an unwanted result that, I assume, is possibly more a 'general Stata' graphics engine issue.
I am not sure what to think of it so I would like to ask you to have a look at this issue.
My rather simple example is that I want to draw 256 lines beside each other from left (black) to right (white). The setup is coded like:
```
* Setup
clear
set obs 256
gen id=_n
gen L=id-1
gen x=0
gen y=1
```
Next, I draw the first spike line using:
```
tw spike y x , lw(2pt) la(center) lc("0 0 0") ysiz(1) xsiz(10) ///
	graphreg(m(l-0 r+8 t-1 b-1)) plotreg(lc(none) m(none)) ///
	ylab(0(0)1, nolab notick angle(none)) ysca(lw(none)) xsca(lw(none)) ///
	xlab(0(255)255, labs(9pt) tl(3pt) labgap(0)) xmtick(0(5)255, tl(3pt)) ///
	ytit("RGB L ", orientation(hor) s(14pt) ) xtit("") scale(1) name(rgb_L, replace)
```
which results in:
![Gradient_scale_RGB_L_Lightness_Line1](https://github.com/benjann/addplot/assets/3686136/96234d5d-ef03-41be-abd2-d531289740bf)
next, I loop the next 255 lines with their increasing RGB color code, with:
```
forvalue i = 1(1)255 {
	local fcolours = `""`i' `i' `i'""' // to get the three RGB code numbers
	addplot , nodraw: spike y L if L==`i', lw(2pt) la(center) lc(`fcolours') legend(off) norescaling
}
```
which results in:
![Gradient_scale_RGB_L_Lightness](https://github.com/benjann/addplot/assets/3686136/23ede3f0-719e-4d34-abb4-a4e9e54bd835)
Now, before I adjust this plot to get a more smooth gradient scale, have a look at the first few lines at the left:
![Stata_Addplot_Drawing_with_unwanted_edges](https://github.com/benjann/addplot/assets/3686136/eeffa5ec-dcfa-4bd5-bbbe-7c48114fac58)
You will observe that the first line at x=0 is drawn perfectly black (i.e. RGB [ 0,0,0 ]). This was done using the `tw spike` code to create the first graph. But, all lines to the right are not drawn in the same manner but have a 'ragged' line. These were added using `addplot`, I indicate the unwanted 'raggedness' here with blue and orange:
![Stata_Addplot_Drawing_with_unwanted_edges_edited](https://github.com/benjann/addplot/assets/3686136/9c010cfb-93c4-484d-8420-02da3f59c600)
which is rather strange given the fact that I draw a line and not an object that would have a fill color and a line color.
Note that I get the same result when I draw this plot using `tw bar` with options set to `lw(none) la(inside)` or `tw scatteri` .

Can you think of anything in the code of `addplot` that might result in this 'raggedness' at the edge?
Or, would you agree with me that this result is something caused by Stata's graphics engine?
(In which case I want to write Stata Technical support about it.)

Best,
Eric

**Comment by benjann** [comment]
This has nothing to do with `addplot`; it is an artifact of translation to bitmap (e.g. PNG, JPEG, ...). If you export to PDF you will see that all spikes look the same. The reason why the effect is different for the first spike is because the first spike actually is 100 spikes printed on top of each other. Apparently, this seems to make a difference for the translation to bitmap. If you use command 
```
tw spike y x in 1, lw(2pt) la(center) lc("0 0 0") ysiz(1) xsiz(10) ///
	graphreg(m(l-0 r+8 t-1 b-1)) plotreg(lc(none) m(none)) ///
	ylab(0(0)1, nolab notick angle(none)) ysca(lw(none)) xsca(lw(none)) ///
	xlab(0(255)255, labs(9pt) tl(3pt) labgap(0)) xmtick(0(5)255, tl(3pt)) ///
	ytit("RGB L ", orientation(hor) s(14pt) ) xtit("") scale(1) name(rgb_L, replace)
```
to generate the first spike (note the `in 1`), then also the first spike will be blurred.
ben

**Comment by ericmelse** [comment]
Indeed, after exercising with the various export formats I can only agree with you. I was not aware that the issue of 'ragging borders' does not occur with a PDF export. So, I used a PDF editing tool to tweak the result PDF and next export that to a PNG file, like:
![mata_ColrSpace_LCh_100steps_yellow_blue_chrom40_L80t50s_w1edit_2](https://github.com/benjann/addplot/assets/3686136/9d380cdd-1f56-4be4-8c4d-f3256e861f3c)
This result is visually more close to what I am looking for and does require some manual work which I rather would prevent. But, to get this visual result is rewarding. I can optimize this further.
Many thanks!
